management:
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
       health:
         show-details: always
  trace:
    http:
      enabled: true

server:
  compression:
    enabled: true
    excluded-user-agents: 
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
    
spring:
  cloud:
    services:
      registrationMethod: direct