management:
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
       health:
         show-details: always
  trace:
    http:
      enabled: true

spring:
  http:
    converters:
      preferred-json-mapper: gson