#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#    endpoint:
#       health:
#         show-details: always
#  trace:
#    http:
#      enabled: true

server:
  compression:
    enabled: true
    excluded-user-agents: 
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
    

spring:
#  application:
#    name: adperformance
  http:
    converters:
      preferred-json-mapper: gson
  main:
    allow-bean-definition-overriding: true

  zipkin:
    enabled: false
  sleuth:
    messaging:
      enabled: false
      kafka:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: auditevents,beans,conditions,configprops,env,health,heapdump,info,loggers,metrics,sessions,shutdown,threaddump,prometheus
